// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0iS9S8k0VEFEYgSmlpzwbdy3kAUVg0ak',
    appId: '1:691664278594:web:fcae27a2b0aa06383849db',
    messagingSenderId: '691664278594',
    projectId: 'fir-flutter-codelab-cd071',
    authDomain: 'fir-flutter-codelab-cd071.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-cd071.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ-Jnasp2CpD8TNupTzeNi67wsfJpa8ZA',
    appId: '1:691664278594:android:27e18371db0cc1123849db',
    messagingSenderId: '691664278594',
    projectId: 'fir-flutter-codelab-cd071',
    storageBucket: 'fir-flutter-codelab-cd071.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEKrYiD00Irk6-V1Ul4Noos8efLzRpwE',
    appId: '1:691664278594:ios:814bfa488bb4453f3849db',
    messagingSenderId: '691664278594',
    projectId: 'fir-flutter-codelab-cd071',
    storageBucket: 'fir-flutter-codelab-cd071.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEKrYiD00Irk6-V1Ul4Noos8efLzRpwE',
    appId: '1:691664278594:ios:814bfa488bb4453f3849db',
    messagingSenderId: '691664278594',
    projectId: 'fir-flutter-codelab-cd071',
    storageBucket: 'fir-flutter-codelab-cd071.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}